### ISSUE TITLE
2d17483aa8d7e19da0ebc8560f84074ce6670a31 breaks /work/pages_tab?work_id=__#create-page

### ISSUE THREAD

**Issue by srl295** [benwbrum/fromthepage#254]
( Plus side: learned how `git bisect` works, much less _running a rails migrate / server each time_ [this](http://stackoverflow.com/a/25677550/185799) works .)

ANyways. @kolking ’s 2d17483aa8d7e19da0ebc8560f84074ce6670a31 breaks me. I get a `[Error] TypeError: $('.input-file').inputFile is not a function. (In '$('.input-file').inputFile()', '$('.input-file').inputFile' is undefined)` and a spinning wheel o' lightboxed death trying to add a new image.  Just FYI.

**Comment by kolking** [comment]
@srl295 could you please provide me with more details on that? I need to know the page (url) where you got this error and your browser version.

**Comment by srl295** [comment]
Url is in the issue title.  Browser is safari latest on El Capitan- well get exact version.

**Comment by kolking** [comment]
@srl295 I would appreciate if you could try the same in a different browser - Chrome or Firefox. Just to make sure it's not a browser specific issue.

**Comment by srl295** [comment]
Safari: Version 9.0.1 (11601.2.7.2)

**Comment by saracarl** [comment]
@tbl73 Can you see if you can reproduce this?

**Comment by srl295** [comment]
I also didn't re-check this yet.

**Comment by tbl73** [comment]
Is this breaking when you upload a file image for a blank page (added directly to a work)?  It seems to be working fine in Chrome at this point - I wasn't able to reproduce.

**Comment by saracarl** [comment]
Is this only with a iphone/mobile device?  The original description implies that, but I'm not sure.
