### ISSUE TITLE
500 error loading transcription page for spreadsheet project.

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#5194]
Going to this page:
https://fromthepage.com/umja/talmud-torah-of-minneapolis-records/umja0054-4-1/transcribe/34798039

I get a 500 error:

```
I, [2026-01-06T17:10:58.735623 #1820437]  INFO -- :   Parameters: {"user_slug"=>"umja", "collection_id"=>"talmud-torah-of-minneapolis-records", "work_id"=>"umja0054-4-1", "page_id"=>"34798039"}

I, [2026-01-06T17:10:58.821941 #1820437]  INFO -- : Completed 500 Internal Server Error in 85ms (ActiveRecord: 26.9ms (18 queries, 1 cached) | GC: 4.2ms)
F, [2026-01-06T17:10:58.823595 #1820437] FATAL -- :   
NoMethodError (undefined method `each' for nil):
  
app/interactors/transcription_field/lib/utils.rb:22:in `block (3 levels) in table_cells_to_field_cells'
app/interactors/transcription_field/lib/utils.rb:19:in `each_value'
app/interactors/transcription_field/lib/utils.rb:19:in `block (2 levels) in table_cells_to_field_cells'
app/interactors/transcription_field/lib/utils.rb:9:in `each'
app/interactors/transcription_field/lib/utils.rb:9:in `block in table_cells_to_field_cells'
app/interactors/transcription_field/lib/utils.rb:4:in `each_value'
app/interactors/transcription_field/lib/utils.rb:4:in `table_cells_to_field_cells'
app/controllers/transcribe_controller.rb:604:in `handle_transcription_json_data'
app/controllers/transcribe_controller.rb:583:in `handle_display_page_data'
app/controllers/transcribe_controller.rb:20:in `display_page'
app/controllers/application_controller.rb:70:in `switch_locale'

```

I suspect it's caused by #5192

**Comment by benwbrum** [comment]
The error I'm seeing is this:
```
I, [2026-01-14T18:22:00.170086 #1293014]  INFO -- : Processing by TranscribeController#display_page as HTML
I, [2026-01-14T18:22:00.170121 #1293014]  INFO -- :   Parameters: {"user_slug"=>"umja", "collection_id"=>"talmud-torah-of-minneapolis-records", "work_id"=>"umja0054-4-1", "page_id"=>"34798039"}
I, [2026-01-14T18:22:00.216556 #1293014]  INFO -- : Completed 500 Internal Server Error in 46ms (ActiveRecord: 18.4ms (18 queries, 1 cached) | GC: 0.1ms)
F, [2026-01-14T18:22:00.218186 #1293014] FATAL -- :   
NoMethodError (undefined method `each' for nil):
  
app/interactors/transcription_field/lib/utils.rb:22:in `block (3 levels) in table_cells_to_field_cells'
app/interactors/transcription_field/lib/utils.rb:19:in `each_value'
app/interactors/transcription_field/lib/utils.rb:19:in `block (2 levels) in table_cells_to_field_cells'
app/interactors/transcription_field/lib/utils.rb:9:in `each'
app/interactors/transcription_field/lib/utils.rb:9:in `block in table_cells_to_field_cells'
app/interactors/transcription_field/lib/utils.rb:4:in `each_value'
app/interactors/transcription_field/lib/utils.rb:4:in `table_cells_to_field_cells'
app/controllers/transcribe_controller.rb:604:in `handle_transcription_json_data'
app/controllers/transcribe_controller.rb:583:in `handle_display_page_data'
app/controllers/transcribe_controller.rb:20:in `display_page'
```

The data appears not to be migrated in this page, so why isn't the on-demand migration succeeding?
```
3.3.5 :008 > page = Page.find 34798039
 => 
#<Page:0x000072ba834d02a0
... 
3.3.5 :009 > page.table_cells.count
 => 780 
3.3.5 :010 > page.transcription_json
 => nil 
```

The [relevant line](https://github.com/benwbrum/fromthepage/blob/development/app/interactors/transcription_field/lib/utils.rb#L22) appears to be looping through a map of spreadsheet cells.

**Comment by benwbrum** [comment]
This is happening because we cannot find any spreadsheet columns for the page, since they have gone missing from the project:

<img width="2374" height="1646" alt="Image" src="https://github.com/user-attachments/assets/2679676e-be36-4b20-ae3c-5f37f0f43953" />

Here are the column headers in case we need to restore them:
```
{"header-date-if-listed"=>1,
 "Day enroll"=>82,
 "No."=>41,
 "Last name"=>41,
 "First name of child (English)"=>41,
 "First name of child (Hebrew)"=>41,
 "First name of parent (English)"=>41,
 "First name of parent (Hebrew)"=>41,
 "Residential address"=>41,
 "Residential phone"=>41,
 "Occupation parent"=>41,
 "Business address"=>41,
 "Business phone"=>41,
 "Place of child's birth"=>41,
 "Birthday"=>41,
 "Grade at school"=>41,
 "Fees"=>41,
 "Previous schooling"=>41,
 "Remarks"=>41} 
```

**Comment by WillNigel23** [comment]
@benwbrum @saracarl 

It seems that the SpreadsheetColumn were missing in db. The solution here is to re-create the spreadsheet columns under the same label, and our transcription_json migration should work.

I added them back through the frontend, the issue should now be resolved.

https://fromthepage.com/umja/talmud-torah-of-minneapolis-records/umja0054-4-1/transcribe/34798039

**Comment by benwbrum** [comment]
This looks great!
